// Generated by png2c [(c) Oleg Vaskevich 2013]

#include <pgmspace.h>

#ifndef _chains_H_
#define _chains_H_

extern const unsigned int chains_width;
extern const unsigned int chains_height;
extern const int chains_size;
extern const unsigned short chains[] PROGMEM;

#endif

