// Generated by png2c [(c) Oleg Vaskevich 2013]

#include <pgmspace.h>

#ifndef _droplets_H_
#define _droplets_H_

extern const unsigned int droplets_width;
extern const unsigned int droplets_height;
extern const int droplets_size;
extern const unsigned short droplets[] PROGMEM;

#endif

