// Generated by png2c [(c) Oleg Vaskevich 2013]

#include <pgmspace.h>

#ifndef _fox_H_
#define _fox_H_

extern const unsigned int fox_width;
extern const unsigned int fox_height;
extern const int fox_size;
extern const unsigned short fox[] PROGMEM;

#endif

