// Generated by png2c [(c) Oleg Vaskevich 2013]

#include <pgmspace.h>

#ifndef _lock_H_
#define _lock_H_

extern const unsigned int lock_width;
extern const unsigned int lock_height;
extern const int lock_size;
extern const unsigned short lock[] PROGMEM;

#endif

