// Generated by png2c [(c) Oleg Vaskevich 2013]

#include <pgmspace.h>

#ifndef  stars_H_
#define  stars_H_

extern const unsigned int stars_width;
extern const unsigned int stars_height;
extern const int stars_size;
extern const unsigned short stars[] PROGMEM;

#endif

